#!/bin/bash

if [ -z "$1" ]; then
  WAITFORJOB=""
else
  WAITFORJOB="$1"
fi

# prepare and execute ensemble runs
max_i="$((${LM_C_ENS_NUMBER}-1))"
for i in $(seq -f "%04g" 0 ${max_i}) ; do

  mkdir -p $i #Directory for ensemble member i
  cd $i

  # cleanup
  ln -sf ../clean
  ./clean

  # link necessary paths and exe
  ln -sf ../run
  ln -sf ../output/$i output
  ln -sf ../input
  ln -sf ../cosmo

  #submit the run
  ./run ${WAITFORJOB}
  cd ..
done
