#!/bin/bash

# CCLM2 EURO-CORDEX 12km (0.5° for CLM) configuration

# CAUTION: Sourcing is done from the DECREMENT root dir
#          so path for sourcing are relative to there.


# ===================================================
#                   COSMO
# ===================================================

# Grid-specific settings
# ----------------------
source simulation_configs/SIMULATION_EU_12km_2km_scClim

# General settings
# ----------------------

export COSMO_TARGET="gpu"            # COSMO target architecture

export EXE_COSMO="../bin/cosmo_gpu"  # name of the executables
#export EXE_INT2LM="../bin/int2lm"

export SB_PARTS="00_get_data 10_ifs2lm 20_cclm2_c 50_pack_data 60_chain"
export LM_COMPRESS_DIRS="cclm2_c/1h_2D cclm2_c/24h cclm2_c/3h_3D_zlev"
export cclm2_c_deps="previous_cclm2_c current_ifs2lm"
export chain_deps="previous_cclm2_c"

if [[ $COSMO_TARGET == "cpu" ]]; then
    export NQS_NXLM_C=6               # number of CPUs in x direction (12 per node on daint-gpu)
    export NQS_NYLM_C=6               # number of CPUs in y direction
else
    export NQS_NXLM_C=2               # number of CPUs in x direction (12 per node on daint-gpu)
    export NQS_NYLM_C=2               # number of CPUs in y direction
fi


# ===================================================
#                   CESM
# ===================================================

# General settings
# ----------------------
export CLM_model_version='"release-clm5.0.35-52-gb3e26f715"' # tag of the CLM executable (from a CTSM checkout)
export CLM_COMPILER=gcc
export CLM_pio_typename='"netcdf"'
export CLM_C_NTASKS=12   # only used on cpu, else use idling cpus, i.e. (2x2)x(12-1)=44 tasks
export CLM_paramfile="clm5_params.c171117.nc" # or clm50_params.c211112.nc

# Grid-specific settings
# ----------------------
export CLM_case_title='"clm5.0.gnu-oasis.I2000Clm50SpGs.CLM_USRDAT.eur_0.1.cclm2"' # case name of the CLM exe, ends up in netcdf attributes
export CLM_case_id='"clm5.0_eur0.1"' # ends up in output file name and netcdf attributes
export CLM_nx=932 # longitudes (ni) 
export CLM_ny=427 # latitudes (nj) 

export CLM_domainfile="domain_EU-CORDEX_0.1_lon360.nc"
export CLM_oasisdummy="OASIS_dummy_0.1_lon360.nc"
export CLM_fsurdat="surfdata_0.1x0.1_EUR_hist_16pfts_Irrig_CMIP6_simyr2005_c230523.nc"
export CLM_finidat="clmi.I2000Clm50BgcCrop.2011-01-01.1.9x2.5_gx1v7_gl4_simyr2000_c190312.nc"

# Output variables, frequency and averaging
# ----------------------
export CLM_hist_empty_htapes=.true. # true = turn off default output variables on h0

# vars tape1-3: temps and fluxes SWdn, SWup, LWdn, LWup, SH, LH, G
# TREFMNAV TREFMXAV daily min/max of average 2-m temperature
# Tair_from_atm atmospheric air temperature received from atmosphere (pre-downscaling)
export CLM_hist_fincl1="'TBOT','Tair_from_atm','TSKIN','TG','TV','TSOI','TSA','FSDS','FSR','FLDS','FIRE','FSH','EFLX_LH_TOT','FGR'"
export CLM_hist_fincl2="'TBOT','Tair_from_atm','TSA','FSDS'"
export CLM_hist_fincl3="'TBOT','Tair_from_atm','TSA','FSDS'"

export CLM_hist_avgflag_pertape="'A','A','X'"       # averaging over the output interval (A=avg, I=inst, X=max) 
export CLM_hist_dov2xy=".true.,.false.,.true."      # true = 2D (grid cell level), false = 1D vector (pft output)

export CLM_hist_mfilt="12,365,8760"                 # number of values per file
export CLM_hist_nhtfrq="0,-24,-1"                   # output frequency (0=monthly, -24=daily, -1=hourly)


# ===================================================
#                   CCLM2
# ===================================================

export NQS_ELAPSED_CCLM2_C=00:30:00    # maximum wall-clock time (HH:mm:ss)
