#!/bin/bash

# # This is an example file with some common settings.
# # Really take it as an example, not a default settings file.
# # It won't be loaded as is, first copy it as `user_settings` and then
# # modify it at will.
# # These settings will take precedence over any other:
# # user_settings > config > defaults

# # COSMO target architecture
# export COSMO_TARGET="gpu"

# # Scheduler account
# export ACCOUNT="pr133"

# # Name of the executables
# export EXE_INT2LM="./int2lm"
# export EXE_COSMO="./cosmo"

# # Global Simulation Dates (YYYY-MM-DDTHH:00)
# export LM_INI_DATE="2011-01-01T00:00"   # Initial date of simualtion
# export LM_START_DATE="2011-01-01T00:00"   # use if you don't want to start from LM_INI_DATE
# export LM_FIN_DATE="2011-01-03T00:00"   # Overall end of simulation

# # Chaining interval, i.e., how long one simualtion chunk will be. If unset, run in one chunk
# export LM_CHAIN_INTERVAL=1day # Anything human readable like "2 hours", "1 month", ...

# # List of output folders to compress and pack (use spaces between the folders)
# export LM_COMPRESS_DIRS="lm_c/1h_2D lm_c/24h lm_c/3h_3D_zlev lm_f/1h_2D lm_f/24h lm_f/3h_3D_zlev"

# # Parts that will be executed. Same as folder names.
# # CAUTION: make sure the order of the parts is compatible with the dependencies,
# # i.e. any dependency of a part should be submitted before the said part
# export SB_PARTS="00_get_data 10_ifs2lm 20_lm_c"

# # Dependencies
# # The format is xxx_deps="current_yyy previous_zzz ..."
# # where xxx, yyy and zzz are valid "short names" of parts to be ran,
# # i.e without the "kk_" leading digits of the name.
# export get_data_deps=""
# export ifs2lm_deps="previous_ifs2lm current_get_data"
# export lm_c_deps="previous_lm_c current_ifs2lm"
# export chain_deps="previous_lm_c"

# # Ensemble settings
# export LM_NL_ITYPE_PERT_C=1
# export LM_NL_RPERTURB_C=0.00001
# export LM_NL_ENS_NUMBER_C=10 #Set the number of ensemble members. Leave commented to use normal mode.
