#!/bin/bash

# These settings will take precedence over any other:
# user_settings > config > defaults

# Settings: CCLM2 production setup, future (with MPI-ESM-HR ssp1 BC synced and linked)
# CCLM2 only

# Experiment info for COSMO's IOCTL and INT2LM's INPUT
# -----------
export LM_NL_YNCGLOB_PROJECT_ID='"FeedBaCks"'
export LM_NL_YNCGLOB_EXPERIMENT_ID='"EUR-11_ssp1"'
export LM_NL_YNCGLOB_CONTACT='"Petra Sieber (petra.sieber@env.ethz.ch)"'

# CLM surface dataset
export CLM_fsurdat="surfdata_0.1x0.1_EUR11_hist_16pfts_Irrig_CMIP6_simyr2005_c230523_eunisl3_ssp1_corr.nc"


# Scheduler account and user
# -----------
export ACCOUNT="s1256"
export CLM_username='"psieber"'


# Global Simulation Dates (YYYY-MM-DDTHH:00)
# -----------
export LM_INI_DATE="2034-01-01T00:00"     # Initial date of simualtion
export LM_START_DATE="2034-01-01T00:00"   # Use if you don't want to start from LM_INI_DATE
export LM_FIN_DATE="2051-01-01T00:00"     # Overall end of simulation

# Chaining interval, i.e., how long one simualtion chunk will be. If unset, run in one chunk
export LM_CHAIN_INTERVAL="1 year" # Anything human readable like "2 hours", "1 month", "1 day", "" to run in one chunk


# Parts to be executed (also in config)
# ----------------------
#export SB_PARTS="10_ifs2lm 20_cclm2_c 60_chain"
#export SB_PARTS="10_ifs2lm 60_chain"             # generate COSMO boundary conditions with INT2LM
export SB_PARTS="20_cclm2_c 60_chain"            # CCLM2 only (chain needed for restarts)

# Link existing bc files
cd 10_ifs2lm/output
ln -sf /scratch/snx3000/psieber/cclm2_EUR11_future_BC/10_ifs2lm/output/* .
cd ../..


# Maximum wall-clock time (HH:mm:ss) - for 6-month chunks
# ----------------------
#export NQS_ELAPSED_GET_DATA=06:00:00   # default 01:00:00
export NQS_ELAPSED_IFS2LM=02:00:00     # default 00:30:00
export NQS_ELAPSED_CCLM2_C=24:00:00    # default 01:00:00


#====================================
#====================================

# Link existing bc files
#export SB_PARTS="20_cclm2_c"
#cd 10_ifs2lm/output
#rm -f *
#ln -s /scratch/snx3000/psieber/cclm2_EUR11_2004-summer/10_ifs2lm/output/* .
#cd ../..

# Link cas files instead of running 00_get_data which copies them
# Modify file name in symlinks to match the expectations of INT2LM (new 14 digit format)
#years="$(seq 2034 2051)"
#months=(01 02 03 04 05 06 07 08 09 10 11 12)
#cd 00_get_data/output
#for y in $years; do
#    for m in ${months[@]}; do
#        ln -sf $SCRATCH/gcm_forcing/MPI-ESM-HR/ssp126_r1i1p1f1/europe/${y}/${m}/* .
#        for filename in cas${y}${m}*.nc; do mv $filename ${filename%.*}0000.nc; done;
#    done
#done
#cd ../..

#export LM_NL_IDBG_LEVEL_C=6 # 6, increase COSMO debug level for more output in cosmo*.out


#====================================
#====================================

# Executables and albedo coupling
# -----------
# New executables
#export EXE_COSMO="../bin/cosmo_gpu"
#export EXE_CESM="../bin/cesm.exe"
#cd 20_cclm2_c/Defaults
#rm -f cclm2_namcouple_defaults.sh
#ln -s cclm2_namcouple_defaults_2alb.sh cclm2_namcouple_defaults.sh
#cd ../..

# Old executables
#export EXE_COSMO="../bin/cosmo_gpu_noIO_1alb"
#export EXE_CESM="../bin/cesm_1alb.exe"
#export NQS_NIOLM_C=0                             # IO has to be turned off for the old COSMO exe
#cd 20_cclm2_c/Defaults
#rm -f cclm2_namcouple_defaults.sh
#ln -s cclm2_namcouple_defaults_1alb.sh cclm2_namcouple_defaults.sh
#cd ../..

# COSMO standalone
# ----------------------
# Link simulation config from terminal!
# rm -f config
# ln -s ./simulation_configs/SIMULATION_EU_12km_COSMO_COPAT2

#export SB_PARTS="10_ifs2lm 20_lm_c 60_chain"
#export SB_PARTS="20_lm_c"
#export NQS_ELAPSED_LM_C=00:30:00

# Tests
# -----------
# Try using Eric's cosmo executable for cpu (did not work, missing access to eccodes lib on pr133)
#export EXE_COSMO="/scratch/snx3000/emaison/COSMO-CLM2_sandbox/EU-CORDEX_50km/cosmo"
#export COSMO_TARGET="cpu"            # COSMO target architecture, default gpu

# 10_ifs2lm and 20_cclm2_c
#export LM_NL_EXTPAR_C=extpar_euro_12km_771x771.nc                 # int2lm@2.5.1_demorym
#export LM_NL_EXTPAR_C=extpar_euro_12km_771x771_TCL_S_ORO_MAX.nc   # int2lm@c2sm-features and scClim
#export LM_NL_EXTPAR_C=extpar_12km_europe_771x771.nc                # CCLM2 for itype_albedo=2
#export LM_NL_ITYPE_ALBEDO_C=2                                      # CCLM2 for coupling

# Link existing bc files, 6hr (ETH domain)
#export SB_PARTS="20_cclm2_c 60_chain"
#cd 10_ifs2lm/output
#rm -f *
#ln -s $SCRATCH/COSMO_inputdata/10_ifs2lm_output_ERA5-6hr/* .
#cd ../..

# INT2LM tests
#export NQS_ELAPSED_IFS2LM=01:30:00  # maximum wall-clock time (HH:mm:ss)
#export NQS_NXIFS2LM=4               # number of CPUs in x direction (12 per node on daint-gpu)
#export NQS_NYIFS2LM=6               # number of CPUs in y direction

#export NQS_NXIFS2LM=6               # number of CPUs in x direction (12 per node on daint-gpu)
#export NQS_NYIFS2LM=6               # number of CPUs in y direction

#export NQS_NXIFS2LM=6               # number of CPUs in x direction (12 per node on daint-gpu)
#export NQS_NYIFS2LM=8               # number of CPUs in y direction

#export NQS_NXIFS2LM=8               # number of CPUs in x direction (12 per node on daint-gpu)
#export NQS_NYIFS2LM=8               # number of CPUs in y direction

#export LM_NL_IDBG_LEVEL_C=6 # 6, increase COSMO debug level for more output in cosmo*.out
#export NQS_NIOLM_C=0        # 1 for production, 0 to generate rmp files


# Dependencies
# -----------
# The format is xxx_deps="current_yyy previous_zzz ..."
# where xxx, yyy and zzz are valid "short names" of parts to be ran,
# i.e without the "kk_" leading digits of the name.
#export get_data_deps=""
#export ifs2lm_deps="previous_ifs2lm current_get_data"
#export lm_c_deps="previous_lm_c current_ifs2lm"
#export chain_deps="previous_lm_c"

# Ensemble settings
# -----------
#export LM_NL_ITYPE_PERT_C=1
#export LM_NL_RPERTURB_C=0.00001
#export LM_NL_ENS_NUMBER_C=10 #Set the number of ensemble members. Leave commented to use normal mode.



