#!/bin/bash

# These settings will take precedence over any other:
# user_settings > config > defaults

# Settings: CCLM2 production setup, historical (with ERA5 forcing copied from store)


# Experiment info for COSMO's IOCTL and INT2LM's INPUT
# -----------
export LM_NL_YNCGLOB_PROJECT_ID='"FeedBaCks"'
export LM_NL_YNCGLOB_EXPERIMENT_ID='"Test"'
export LM_NL_YNCGLOB_CONTACT='"Petra Sieber (petra.sieber@env.ethz.ch)"'


# Scheduler account and user
# -----------
export ACCOUNT="s1256"
export CLM_username='"psieber"'


# Global Simulation Dates (YYYY-MM-DDTHH:00)
# -----------
export LM_INI_DATE="2004-01-01T00:00"     # Initial date of simualtion
#export LM_START_DATE="2004-01-01T00:00"   # use if you don't want to start from LM_INI_DATE
export LM_FIN_DATE="2004-01-05T00:00"     # Overall end of simulation

export LM_NL_CZML_SOIL_IN=0.035,0.175,0.64,1.945       # ERA5 soil levels
#export LM_NL_CZML_SOIL_IN=0.035,0.175,0.64,1.775      # 2007-2020 velasque has old data: czml_soil_in=0.035,0.175,0.64,1.775

# Chaining interval, i.e., how long one simualtion chunk will be. If unset, run in one chunk
export LM_CHAIN_INTERVAL="6 months" # Anything human readable like "2 hours", "1 month", "1 day", "" to run in one chunk


# Parts to be executed (also in config)
# ----------------------
#export SB_PARTS="00_get_data 10_ifs2lm 20_cclm2_c 50_pack_data 60_chain"
#export SB_PARTS="00_get_data 10_ifs2lm 20_cclm2_c 60_chain" # generate COSMO boundary conditions with INT2LM
#export SB_PARTS="20_cclm2_c 60_chain" # CCLM2 only (chain needed for restarts)


# Maximum wall-clock time (HH:mm:ss) - for 6-month chunks
# ----------------------
export NQS_ELAPSED_GET_DATA=06:00:00   # default 01:00:00
export NQS_ELAPSED_IFS2LM=20:00:00     # default 00:30:00
export NQS_ELAPSED_CCLM2_C=01:00:00    # default 01:00:00


#====================================
#====================================

# Link existing cas files instead of running 00_get_data which copies them (possible for Jan 2011)
#export SB_PARTS="10_ifs2lm" # generate COSMO boundary conditions with INT2LM
#cd 00_get_data/output
#ln -sf $SCRATCH/COSMO_inputdata/00_get_data_output_ERA5/* .
#cd ../..

# Link existing bc files
export SB_PARTS="20_cclm2_c"
cd 10_ifs2lm/output
ln -sf /scratch/snx3000/psieber/COSMO_boundary/INT2LM_output_ERA5/* .
cd ../..

#export LM_NL_IDBG_LEVEL_C=6 # 6, increase COSMO debug level for more output in cosmo*.out


#====================================
#====================================

# Executables and albedo coupling
# -----------
# New executables
#export EXE_COSMO="../bin/cosmo_gpu"
#export EXE_CESM="../bin/cesm.exe"
#cd 20_cclm2_c/Defaults
#ln -sf cclm2_namcouple_defaults_2alb.sh cclm2_namcouple_defaults.sh
#cd ../..

# Old executables
#export EXE_COSMO="../bin/cosmo_gpu_noIO_1alb"
#export EXE_CESM="../bin/cesm_1alb.exe"
#export NQS_NIOLM_C=0                             # IO has to be turned off for the old COSMO exe
#cd 20_cclm2_c/Defaults
#ln -sf cclm2_namcouple_defaults_1alb.sh cclm2_namcouple_defaults.sh
#cd ../..

# COSMO standalone
# ----------------------
# Link simulation config from terminal!
# ln -sf ./simulation_configs/SIMULATION_COSMO-EUR11_ERA5 config

#export SB_PARTS="10_ifs2lm 20_lm_c 60_chain"
#export SB_PARTS="20_lm_c"
#export NQS_ELAPSED_LM_C=00:30:00

# Tests
# -----------
# Try using Eric's cosmo executable for cpu (did not work, missing access to eccodes lib on pr133)
#export EXE_COSMO="/scratch/snx3000/emaison/COSMO-CLM2_sandbox/EU-CORDEX_50km/cosmo"
#export COSMO_TARGET="cpu"            # COSMO target architecture, default gpu

# 10_ifs2lm and 20_cclm2_c
#export LM_NL_EXTPAR_C=extpar_euro_12km_771x771.nc                 # int2lm@2.5.1_demorym
#export LM_NL_EXTPAR_C=extpar_euro_12km_771x771_TCL_S_ORO_MAX.nc   # int2lm@c2sm-features and scClim
#export LM_NL_EXTPAR_C=extpar_12km_europe_771x771.nc                # CCLM2 for itype_albedo=2
#export LM_NL_ITYPE_ALBEDO_C=2                                      # CCLM2 for coupling

# Link existing bc files, 6hr (ETH domain)
#export SB_PARTS="20_cclm2_c 60_chain"
#cd 10_ifs2lm/output
#ln -sf $SCRATCH/COSMO_inputdata/10_ifs2lm_output_ERA5-6hr/* .
#cd ../..

# INT2LM tests
#export NQS_ELAPSED_IFS2LM=01:30:00  # maximum wall-clock time (HH:mm:ss)
#export NQS_NXIFS2LM=4               # number of CPUs in x direction (12 per node on daint-gpu)
#export NQS_NYIFS2LM=6               # number of CPUs in y direction

#export NQS_NXIFS2LM=6               # number of CPUs in x direction (12 per node on daint-gpu)
#export NQS_NYIFS2LM=6               # number of CPUs in y direction

#export NQS_NXIFS2LM=6               # number of CPUs in x direction (12 per node on daint-gpu)
#export NQS_NYIFS2LM=8               # number of CPUs in y direction

#export NQS_NXIFS2LM=8               # number of CPUs in x direction (12 per node on daint-gpu)
#export NQS_NYIFS2LM=8               # number of CPUs in y direction

#export LM_NL_IDBG_LEVEL_C=6 # 6, increase COSMO debug level for more output in cosmo*.out
#export NQS_NIOLM_C=0        # 1 for production, 0 to generate rmp files


# Dependencies
# -----------
# The format is xxx_deps="current_yyy previous_zzz ..."
# where xxx, yyy and zzz are valid "short names" of parts to be ran,
# i.e without the "kk_" leading digits of the name.
#export get_data_deps=""
#export ifs2lm_deps="previous_ifs2lm current_get_data"
#export lm_c_deps="previous_lm_c current_ifs2lm"
#export chain_deps="previous_lm_c"

# Ensemble settings
# -----------
#export LM_NL_ITYPE_PERT_C=1
#export LM_NL_RPERTURB_C=0.00001
#export LM_NL_ENS_NUMBER_C=10 #Set the number of ensemble members. Leave commented to use normal mode.



