#!/bin/bash

# These are the default user settings. Some settings are also present
# in the simulation configuration file. The values in this file will
# take precedence over the default settings of the configuration so
# use that file to overwrite any config setting you'd like to change,
# like nodes distribution, wall time, parts to be ran, etc... The idea
# is to leave the configuration file untouched in order to facilitate
# git tracking.

# COSMO target architecture
export COSMO_TARGET="gpu"
if [[ $COSMO_TARGET == "cpu" ]]; then
    export LM_NL_LCPP_DYCORE=.False.
else
    export LM_NL_LCPP_DYCORE=.True.
fi

# Scheduler account
export ACCOUNT="pr94"

# Name of the executables
export EXE_INT2LM="./int2lm"
export EXE_COSMO="./cosmo"

# Spack specifications. Leave empty if executables are manually copied
export LM_INT2LM_SPEC=""
export LM_COSMO_SPEC=""

# Global Simulation Dates (YYYY-MM-DDTHH:00)
# export LM_INI_DATE="2011-01-01T00:00"
# export LM_FIN_DATE="2012-01-01T00:00"

# Chaining interval
# export LM_CHAIN_INTERVAL=1month     #Current options: "1year", "1month", "1day".

# List of output folders to compress and pack (use spaces between the folders)
# export LM_COMPRESS_DIRS="lm_c/1h_2D lm_c/24h lm_c/3h_3D_zlev lm_f/1h_2D lm_f/24h lm_f/3h_3D_zlev"

# Parts that will be executed. Same as folder names.
# export SB_PARTS="0_get_data 1_ifs2lm 2_lm_c 3_lm2lm 4_lm_f 5_pack_data 6_chain"
