#!/bin/bash

# These are the default user settings. Some settings are also present
# in the simulation configuration file. The values in this file will
# take precedence over the default settings of the configuration so
# use that file to overwrite any config setting you'd like to change,
# like nodes distribution, wall time, parts to be ran, etc... The idea
# is to leave the configuration file untouched in order to facilitate
# git tracking.

# COSMO target architecture
export COSMO_TARGET="gpu"
if [[ $COSMO_TARGET == "cpu" ]]; then
    export LM_NL_LCPP_DYCORE=.False.
else
    export LM_NL_LCPP_DYCORE=.True.
fi

# Scheduler account
export ACCOUNT="pr94"

# Name of the executables
export EXE_INT2LM="./int2lm"
export EXE_COSMO="./cosmo"

# Will environemt using "spack load" commans.
export LM_INT2LM_SPEC="int2lm@c2sm-master%nvhpc slave=daint"
export LM_COSMO_SPEC="cosmo@c2sm-master%nvhpc cosmo_target=gpu real_type=double +cppdycore"

# Global Simulation Dates (YYYY-MM-DDTHH:00)
# export LM_INI_DATE="2011-01-01T00:00"   # Initial date of simualtion
# if [ -z $LM_BEGIN_DATE ]; then #if needed so LM_BEGIN_DATE set in 6_chain does not get overwritten
# export LM_BEGIN_DATE="2011-01-01T00:00" # Startdate of the current step
#                                         # use if you dont want to start a step from the initdate
# fi
# export LM_FIN_DATE="2011-01-03T00:00"   # Overall end of simulation

# Chaining interval, i.e., how long one simualtion step will be. If unset, run in one chunk
# export LM_CHAIN_INTERVAL=1day     #Current options: "1year", "1month", "1day".

# List of output folders to compress and pack (use spaces between the folders)
# export LM_COMPRESS_DIRS="lm_c/1h_2D lm_c/24h lm_c/3h_3D_zlev lm_f/1h_2D lm_f/24h lm_f/3h_3D_zlev"

# Parts that will be executed. Same as folder names.
# export SB_PARTS="0_get_data 1_ifs2lm 2_lm_c 3_lm2lm 4_lm_f 5_pack_data 6_chain"

# Ensemble settings
# export LM_NL_ITYPE_PERT_C=1
# export LM_NL_RPERTURB_C=0.00001
# export LM_NL_ENS_NUMBER_C=10 #Set the number of ensemble members. Leave commented to use normal mode.
~                                                                                                     
