#!/bin/bash

# These settings will take precedence over any other:
# user_settings > config > defaults


# Scheduler account and user
# -----------
export ACCOUNT="sm61"
export CLM_username='"psieber"'


# Global Simulation Dates (YYYY-MM-DDTHH:00)
# -----------
export LM_INI_DATE="2011-01-01T00:00"     # Initial date of simualtion
export LM_START_DATE="2011-01-01T00:00"   # use if you don't want to start from LM_INI_DATE
export LM_FIN_DATE="2011-01-03T00:00"     # Overall end of simulation

# Chaining interval, i.e., how long one simualtion chunk will be. If unset, run in one chunk
export LM_CHAIN_INTERVAL="" # Anything human readable like "2 hours", "1 month", "" to run in one chunk


# Parts to be executed (also in config)
# ----------------------
#export SB_PARTS="00_get_data 10_ifs2lm 20_cclm2_c 50_pack_data 60_chain"
#export SB_PARTS="00_get_data 10_ifs2lm 20_cclm2_c 60_chain" # generate COSMO boundary conditions with INT2LM
export SB_PARTS="20_cclm2_c 60_chain" # CCLM2 only

export NQS_ELAPSED_CCLM2_C=01:00:00    # maximum wall-clock time (HH:mm:ss)


#====================================

# Tests
# -----------
# Try using Eric's cosmo executable for cpu (did not work, missing access to eccodes lib on pr133)
#export EXE_COSMO="/scratch/snx3000/emaison/COSMO-CLM2_sandbox/EU-CORDEX_50km/cosmo"
#export COSMO_TARGET="cpu"            # COSMO target architecture, default gpu

# Dependencies
# -----------
# The format is xxx_deps="current_yyy previous_zzz ..."
# where xxx, yyy and zzz are valid "short names" of parts to be ran,
# i.e without the "kk_" leading digits of the name.
#export get_data_deps=""
#export ifs2lm_deps="previous_ifs2lm current_get_data"
#export lm_c_deps="previous_lm_c current_ifs2lm"
#export chain_deps="previous_lm_c"

# Ensemble settings
# -----------
#export LM_NL_ITYPE_PERT_C=1
#export LM_NL_RPERTURB_C=0.00001
#export LM_NL_ENS_NUMBER_C=10 #Set the number of ensemble members. Leave commented to use normal mode.



