#!/bin/bash

# cleanup
if [ -f .jobid ]; then
  $(squeue -j `cat .jobid` &>/dev/null) && scancel `cat .jobid`
  sleep 3
  \rm .jobid 2>/dev/null
fi
./clean

cat > job <<EOF_job
#!/bin/bash
#SBATCH --job-name=compress
#SBATCH --output=job.out
#SBATCH --nodes=1
#SBATCH --cpus-per-task=12
#SBATCH --ntasks=1
#SBATCH --partition=${QUEUE}
#SBATCH --time=${NQS_ELAPSED_COMPRESS}
#SBATCH --account=${ACCOUNT}

# Load modules
export OMP_NUM_THREADS=$CORES_PER_NODE
export CRAY_CUDA_MPS=1
module load daint-gpu
module load NCO

# Compress, archive and remove originals
./pack_data.sh ${LM_BEGIN_DATE} ${LM_END_DATE} "${LM_COMPRESS_DIRS}"

EOF_job


# submit job
[[ -n "$1" ]] && dep="--dependency=afterok:${1}" || dep=""
jobid=$(sbatch --parsable -C gpu ${dep} job)

if [[ ($? == 0) && (-n "${jobid}") ]]; then
  echo "${jobid}" > .jobid
  echo "${jobid}"
else
  exit 1
fi
