#!/bin/bash

# cleanup
# -------
if [[ -f .jobid ]]; then
  $(squeue -j `cat .jobid` &>/dev/null) && scancel `cat .jobid`
  sleep 3
  \rm .jobid 2>/dev/null
fi
./clean

# setup job
# ---------
cat > job <<EOF_job
#!/bin/bash -l
#
#SBATCH --job-name=chain
#SBATCH --output=job.out
#SBATCH --time=00:05:00
#SBATCH --nodes=1
#SBATCH --partition=normal
#SBATCH --account=${ACCOUNT}

#Check if we are done. If yes, exit
sEndDate=\$(date -d \${LM_END_DATE} +%s)
sFinDate=\$(date -d \${LM_FIN_DATE} +%s)
if [ \$sEndDate -ge \$sFinDate ] ; then
  echo "done"
  exit 0 
fi

# Swap dates
export LM_BEGIN_DATE=\${LM_END_DATE}
cd ..
./run_daint.sh
EOF_job

# submit job
# ----------
[[ -n "$1" ]] && dep="--dependency=afterok:${1}" || dep=""
jobid=$(sbatch --parsable -C gpu ${dep} job)

if [[ ($? == 0) && (-n "${jobid}") ]]; then
  echo "${jobid}" > .jobid
  echo "${jobid}"
else
  exit 1
fi
