#!/bin/bash
#CCLM2 EURO-CORDEX 50km configuration

# CAUTION: Sourcing is done from the DECREMENT root dir
#          so path for sourcing are relative to there.

# ===================================================
#                   COSMO
# ===================================================

# COSMO related settings are from EU_CORDEX_50km
source simulation_configs/SIMULATION_EU_CORDEX_50km

# Adapt some settings
export SB_PARTS="00_get_data 10_ifs2lm 20_cclm2_c 50_pack_data 60_chain"
export LM_COMPRESS_DIRS="cclm2_c/1h_2D cclm2_c/24h cclm2_c/3h_3D_zlev"
export cclm2_c_deps="previous_cclm2_c current_ifs2lm"
export chain_deps="previous_cclm2_c"

if [[ $COSMO_TARGET == "cpu" ]]; then
    export NQS_NXLM_C=6               # number of CPUs in x direction (12 per node on daint-gpu)
    export NQS_NYLM_C=6               # number of CPUs in y direction
else
    export NQS_NXLM_C=2               # number of CPUs in x direction (12 per node on daint-gpu)
    export NQS_NYLM_C=2               # number of CPUs in y direction
fi

# ===================================================
#                   CESM
# ===================================================

source simulation_configs/CCLM2_EU-CORDEX_50km/clm_c_datm_streams.sh
export CLM_C_NTASKS=12   # only used on cpu, else use idling cpus, i.e. (2x2)x(12-1)=44 tasks
export CLM_COMPIlER=gcc


# ===================================================
#                   CCLM2
# ===================================================

export NQS_ELAPSED_CCLM2_C=00:30:00    # maximum wall-clock time (HH:mm:ss)
