#!/bin/bash
#Simulation setup of L. Hentgen, but driven by ERA5 and with a 4 km intermediate nest
  
# Machine 
# -------
export QUEUE="normal"
export ACCOUNT="pr94"
export RUNCMD="srun"
export CORES_PER_NODE=24
export TASKS_PER_NODE=1
export GPUS_PER_NODE=1
export EXE_INT2LM="./int2lm"
export EXE_COSMO="./cosmo"

# Node config 
# -----------

# 1_ifs2lm
export NQS_NXIFS2LM=8               # number of CPUs in x direction (12 per node on daint-gpu)
export NQS_NYIFS2LM=12              # number of CPUs in y direction
export NQS_NIOIFS2LM=0              # number of CPUs for asyncronous IO
export NQS_ELAPSED_IFS2LM=02:45:00  # maximum wall-clock time (HH:mm:ss)

# 2_lm_c
export NQS_NXLM_C=8                 # number of NODEs in x direction
export NQS_NYLM_C=5                 # number of NODEs in y direction
export NQS_NIOLM_C=0                # number of NODEs for asyncronous IO
export NQS_ELAPSED_LM_C=07:00:00    # maximum wall-clock time (HH:mm:ss)


# 3_lm2lm
export NQS_NXLM2LM=10               # number of CPUs in x direction (12 per node on daint-gpu)
export NQS_NYLM2LM=12               # number of CPUs in y direction
export NQS_NIOLM2LM=0               # number of CPUs for asyncronous IO
export NQS_ELAPSED_LM2LM=08:30:00   # maximum wall-clock time (HH:mm:ss)

# 4_lm_f
export NQS_NXLM_F=12                # number of NODEs in x direction
export NQS_NYLM_F=8                # number of NODEs in y direction
export NQS_NIOLM_F=0                # number of NODEs for asyncronous IO
export NQS_ELAPSED_LM_F=12:00:00    # maximum wall-clock time (HH:mm:ss)

# Parts that will be executed. Same as folder names.
export SB_PARTS="1_ifs2lm 2_lm_c 3_lm2lm 4_lm_f"

# GLOBAL ERA5 grid
# ----------------

# ERA5 
export LM_NL_BC_DATA_PATH=/project/${ACCOUNT}/heimc/data/reanalyses/ERA5_new
export LM_NL_POLPHIIFS=90.0
export LM_NL_POLLAMIFS=180.0
export LM_NL_IEIFS=349
export LM_NL_JEIFS=228
export LM_NL_KEIFS=108
export LM_NL_DLAMIFS=0.28125
export LM_NL_DPHIIFS=0.28125
export LM_NL_PHILUIFS=-31.896944
export LM_NL_PHIROIFS=31.896944
export LM_NL_LAMLUIFS=-70.875
export LM_NL_LAMROIFS=27.0


#Glbal files
#export LM_NL_POLPHIIFS=90.0
#export LM_NL_POLLAMIFS=180.0
#export LM_NL_IEIFS=1280
#export LM_NL_JEIFS=640
#export LM_NL_KEIFS=137
#export LM_NL_DLAMIFS=0.28125
#export LM_NL_DPHIIFS=0.28125
#export LM_NL_PHILUIFS=-89.784874
#export LM_NL_PHIROIFS=89.784874
#export LM_NL_LAMLUIFS=-180
#export LM_NL_LAMROIFS=179.71875

# LM coarse
# ===========

# Grid
# ----

export LM_NL_POLLATLM_C=90.0        # Latitude  of the North pole
export LM_NL_POLLONLM_C=-180.0      # Longitude of the North pole
export LM_NL_EXT_IE_C=2900          # Number of grid points (I: zonal, J: meridional)
export LM_NL_EXT_JE_C=2000          # in your external parameter file (containing topology etc.)
export LM_NL_IELM_C=1524
export LM_NL_JELM_C=994
export LM_NL_KELM_C=60
export LM_NL_DLONLM_C=0.04
export LM_NL_DLATLM_C=0.04
export LM_NL_STARTLAT_TOT_C=-12.28
export LM_NL_STARTLON_TOT_C=-70.12

export LM_NL_EXTPAR_C=extpar_SA_4km.nc #Coarse extpar file in /bin

# Configuration
# -------------


# LM fine 
# =======

# Grid
# ----
export LM_NL_POLLATLM_F=90.0
export LM_NL_POLLONLM_F=-180.0
export LM_NL_EXT_IE_F=2990
export LM_NL_EXT_JE_F=1900
export LM_NL_IELM_F=2310
export LM_NL_JELM_F=1542
export LM_NL_KELM_F=60
export LM_NL_DLONLM_F=0.02
export LM_NL_DLATLM_F=0.02
export LM_NL_STARTLAT_TOT_F=-7.77
export LM_NL_STARTLON_TOT_F=-65.625

export LM_NL_EXTPAR_F=extpar_atlantic_2km.nc


