#!/bin/bash
#EURO-CORDEX 50km configuration

  
# Machine 
# -------
export QUEUE="normal"
export ACCOUNT="pr94"
export RUNCMD="srun"
export CORES_PER_NODE=24
export GPUS_PER_NODE=1
if [[ $COSMO_TARGET == "cpu" ]]; then
    export TASKS_PER_NODE=12
else
    export TASKS_PER_NODE=1
fi
export EXE_INT2LM="./int2lm"
export EXE_COSMO="./cosmo"

# Node config 
# -----------

# 1_ifs2lm
export NQS_NXIFS2LM=1               # number of CPUs in x direction (12 per node on daint-gpu)
export NQS_NYIFS2LM=1               # number of CPUs in y direction
export NQS_NIOIFS2LM=0              # number of CPUs for asyncronous IO
export NQS_ELAPSED_IFS2LM=02:00:00  # maximum wall-clock time (HH:mm:ss)

# 2_lm_c
if [[ $COSMO_TARGET == "cpu" ]]; then
    export NQS_NXLM_C=4               # number of CPUs in x direction (12 per node on daint-gpu)
    export NQS_NYLM_C=3               # number of CPUs in y direction
else
    export NQS_NXLM_C=1               # number of CPUs in x direction (12 per node on daint-gpu)
    export NQS_NYLM_C=1               # number of CPUs in y direction
fi
export NQS_NIOLM_C=0                # number of NODEs for asyncronous IO
export NQS_ELAPSED_LM_C=05:00:00    # maximum wall-clock time (HH:mm:ss)

#5_pack_data
export NQS_ELAPSED_COMPRESS=12:00:00    # maximum wall-clock time (HH:mm:ss)
export LM_COMPRESS_DIRS='lm_c/1h_2D lm_c/24h lm_c/3h_3D_zlev' # List of output folders to compress and pack
                                                              # use spaces between the folders. 

#6_chain
export LM_CHAIN_INTERVAL=1year     #Current options: "1year", "1month", "1day".


# Parts that will be executed. Same as folder names.
export SB_PARTS="0_get_data 1_ifs2lm 2_lm_c 5_pack_data 6_chain"

# ===================================================
#                   CONFIGURE COSMO
# ===================================================

# BC grid
# ----------------

# ERA-Interim 
ln -sf run_ERAInt 0_get_data/run #Link correct copy script 
export LM_NL_BC_DATA_PATH=/project/${ACCOUNT}/ERAinterim
export LM_NL_POLPHIIFS=90.0
export LM_NL_POLLAMIFS=180.0
export LM_NL_IEIFS=512
export LM_NL_JEIFS=256
export LM_NL_KEIFS=60
export LM_NL_DLAMIFS=0.703125
export LM_NL_DPHIIFS=0.703125
export LM_NL_PHILUIFS=-89.46282
export LM_NL_PHIROIFS=89.46282
export LM_NL_LAMLUIFS=-180
export LM_NL_LAMROIFS=179.2969
export LM_NL_CZML_SOIL_IN=0.015,0.1,0.405,1.205,
export LM_NL_LUSE_T_SKIN=.False.
if [[ $COSMO_TARGET == "cpu" ]]; then
    export LM_NL_LCPP_DYCORE=.False.
else
    export LM_NL_LCPP_DYCORE=.True.
fi


#COSMO Levels
export LM_VCFLAT=11430.0
export LM_VCOORD_D=22700.00,20800.00,19100.00,17550.00,16150.00,14900.00,13800.00,12785.00,11875.00,11020.00,10205.00,9440.00,8710.00,8015.00,7355.00,6725.00,6130.00,5565.00,5035.00,4530.00,4060.00,3615.00,3200.00,2815.00,2455.00,2125.00,1820.00,1545.00,1295.00,1070.00,870.00,695.00,542.00,412.00,303.00,214.00,143.00,89.00,49.00,20.00,0.00


# 2_lm_c
# ===========

# Grid
# ----
export LM_NL_POLLATLM_C=39.25        # Latitude  of the North pole
export LM_NL_POLLONLM_C=-162.0      # Longitude of the North pole
export LM_NL_EXT_IE_C=153           # Number of grid points (I: zonal, J: meridional)
export LM_NL_EXT_JE_C=159           # in your external parameter file (containing topology etc.)
export LM_NL_IELM_C=132             # Number of grid points (I: zonal, J: meridional)
export LM_NL_JELM_C=129             # and number of vertical levels
export LM_NL_KELM_C=40              # of the coarse grid
export LM_NL_DLONLM_C=0.440         # Delta longitude (in degrees)
export LM_NL_DLATLM_C=0.440         # Delta latitude  (in degrees)
export LM_NL_STARTLON_TOT_C=-33.93  # Starting longitude left
export LM_NL_STARTLAT_TOT_C=-28.93  # Starting latitude south (bottom-left corner of the coarse grid)
                                    # needs to be within the boundaries of the
                                    # ERA5/ERAinterim data above AND co-located with the extpar data

#RUNCTL
export LM_NL_DT_C=300                         # Time Step

#DYNCTL
export LM_NL_RDHEIGHT_C=11000
export LM_NL_RLWIDTH_C=500000
export LM_NL_NRDTAU_C=6
export LM_NL_L_DIFF_SMAG_C=.False.
export LM_NL_LDIFF_COLD_POOLS_C=.False.
export LM_NL_HD_CORR_U_BD_C=0.0
export LM_NL_HD_CORR_T_BD_C=0.0
export LM_NL_HD_CORR_P_BD_C=0.0
export LM_NL_HD_CORR_TRCR_BD_C=0.0
export LM_NL_HD_CORR_U_IN_C=0.25
export LM_NL_HD_CORR_T_IN_C=0.0
export LM_NL_HD_CORR_P_IN_C=0.0
export LM_NL_HD_CORR_TRCR_IN_C=0.0

#PHYCTL
export LM_NL_ITYPE_GSCP_C=3
export LM_NL_LCONV_C=.True.
export LM_NL_LSSO_C=.True.
export LM_NL_HINCRAD_C=1.0
export LM_NL_ICO2_RAD_C=1
export LM_NL_ITYPE_ALBEDO_C=2
export LM_NL_ITYPE_AEROSOL_C=1

#TUNING
export LM_NL_TKHMIN_C=0.35
export LM_NL_TKMMIN_C=1.0
export LM_NL_RLAM_HEAT_C=0.7
export LM_NL_TUR_LEN_C=500
export LM_NL_V0SNOW_C=22.6
export LM_NL_Q_CRIT_C=4.0
export LM_NL_QC0_C=0.0

#GRIBIN
export LM_NL_HINCBOUND_C=6                # Input frequency of boundary conditions
export LM_NL_LANA_QI_C=.True.
export LM_NL_LAN_RHO_SNOW_C=.False.
export LM_NL_EXTPAR_C=extpar_50km_EU_CORDEX_159x153.nc #Coarse extpar file in /bin

#Async NetCDF I/O
export LM_NL_LASYNC_IO_C=.False.
export LM_NL_NUM_IOPE_PERCOMM_C=0         # 1 if async, 0 if sync I/0



