#!/bin/bash

# Update job status
update_status "running"

#Check if output folder exists
mkdir -p $(readlink output)

# clean
./clean

# Unpack cas file for current month
module unload xalt

pushd output >&/dev/null

# Determine boundary dates
current_date=$(date -d "${LM_YYYY_BEGIN}-${LM_MM_BEGIN}-01T00:00" +%c)
current_date_sec=$(date -d "${current_date}" +%s)
end_date=$(date -d "${LM_YYYY_END}-${LM_MM_END}-01T00:00" +%c)
end_date_sec=$(date -d "${end_date}" +%s)

echo "end_date = ${end_date}"
echo "current_date = ${current_date}"
# cycle over dates by 1 month interval
while ((current_date_sec <= end_date_sec)); do
    YYYY=$(date -d "${current_date}" +%Y)
    MM=$(date -d "${current_date}" +%m)

    # build tar command
    tar_cmd="tar --skip-old-files"
    case ${LM_NL_BC_DATA_TYPE} in
        ERAInt)
            tar_file=${LM_NL_BC_DATA_PATH}/${YYYY}/ERAINT_${YYYY}_${MM}.tar.gz
            tar_cmd+=" --transform 's/caf/cas/' --transform 's/.nc/0000.nc/' -xzvf"
            tar_cmd+=" ${tar_file}  -C ."
            ;;
        ERA5)
            tar_file=${LM_NL_BC_DATA_PATH}/${YYYY}/ERA5_cas_${YYYY}_${MM}.tar
            tar_cmd+=" -xvf ${tar_file}"
            ;;
        ERA5-scClim)
            tar_file=${LM_NL_BC_DATA_PATH}/${YYYY}/ERA5_${YYYY}_${MM}_europe.tar
            tar_cmd+=" --strip-components=1 --transform 's/.nc/0000.nc/' -xvf ${tar_file}"
            ;;
        *)
            echo "LM_NL_BC_DATA_TYPE=${LM_NL_BC_DATA_TYPE} is not valid."
            echo "Currently available choices are 'ERAInt' and 'ERA5'"
            exit 1
            ;;
    esac

    # execute tar command
    echo "running ${tar_cmd}"
    eval ${tar_cmd}

    # cycle dates and make sure the next date lands in the next month
    next_date=$(date -d "${current_date} + 1 month");
    while (($(date -d "${next_date}" +%-m) == $(date -d "${current_date}" +%-m))); do
        next_date=$(date -d "${next_date} + 1 hour")
    done
    current_date=$next_date
    echo "current_date = $current_date"
    current_date_sec=$(date -d "${current_date}" +%s)
done

# Update job status
update_status "done"
