#!/bin/bash

if [ -z "$1" ]; then
  WAITFORJOB=""
else
  WAITFORJOB="$1"
fi


# cleanup
if [ -f .jobid ]; then
  $(squeue -j `cat .jobid` &>/dev/null) && scancel `cat .jobid`
  sleep 3
  \rm .jobid 2>/dev/null
fi
./clean

# setup namelists
cat > INPUT <<EOF
 &CONTRL
  yinput_model='CM',
  hstart=$LM_NL_HSTART,
  hstop=$LM_NL_HSTOP,
  hincbound=1.0,
  ydate_ini='${LM_YYYY_INI}${LM_MM_INI}${LM_DD_INI}${LM_ZZ_INI}0000',
  linitial=.TRUE.,
  lboundaries=.TRUE.,
  ltime_mean=.TRUE.,
  luvcor=.TRUE.,
  idbg_level=3,
  luse_t_skin=.TRUE.,
  nprocx=${NQS_NXIFS2LM}, nprocy=${NQS_NYIFS2LM}, nprocio=${NQS_NIOIFS2LM},
    lfilter_pp=.true.,
  llbc_smooth=.true.,
  lfilter_oro=.false.,
    ilow_pass_oro=4,
      numfilt_oro=1,
      ilow_pass_xso=5,
        lxso_first=.FALSE.,
        numfilt_xso=1,
        rxso_mask=750.0,
    eps_filter=0.1,
      norder_filter=5,
    l_topo_z=.false.,
  l_s_oro=.TRUE.,
  rfill_valley=0.0,
    ifill_valley=7,
  lasync_io=.FALSE.,
  lprog_qi=.TRUE.,
  nincwait=30,
  nmaxwait=300,
  lmulti_layer_lm=.TRUE., lmulti_layer_in=.TRUE.,
  itype_w_so_rel=2, itype_t_cl=1, itype_rootdp=4,
  lforest=.TRUE.,
  lsso=.TRUE.,
  lbdclim=.true.,
  lprog_rho_snow=.false.,
 lvertwind_ini=.TRUE.,
 lvertwind_bd=.TRUE.,
 itype_aerosol = 2,
 itype_albedo = 2,
 /
 &GRID_IN
  pcontrol_fi = 30000.,
  ie_in_tot = $LM_NL_IEIFS, je_in_tot = $LM_NL_JEIFS, ke_in_tot = $LM_NL_KEIFS,
  startlat_in_tot = $LM_NL_PHILUIFS, startlon_in_tot = $LM_NL_LAMLUIFS,
  endlat_in_tot   = $LM_NL_PHIROIFS, endlon_in_tot   = $LM_NL_LAMROIFS,
  pollat_in = $LM_NL_POLPHIIFS, pollon_in = $LM_NL_POLLAMIFS,
  dlat_in = $LM_NL_DPHIIFS, dlon_in = $LM_NL_DLAMIFS,
  ke_soil_in = 3,
  czml_soil_in=0.035, 0.175, 0.640, 1.775,
 /
 &LMGRID
  ielm_tot=$LM_NL_IELM_C, jelm_tot=$LM_NL_JELM_C, kelm_tot=$LM_NL_KELM_C,
  ivctype=2,
  vcflat = 17827.0, !11357.0, !17827.0,
  ke_soil_lm=9,irefatm=2,
  czml_soil_lm=0.005, 0.025, 0.07, 0.16, 0.34, 0.70, 1.47, 2.86, 5.74,  11.50,
  vcoord_d=29798.50,28255.93,26824.04,   25497.39,   24269.35,
     23134.03,   22081.88,   21105.64,   20207.79,   19360.60,
     18576.52,   17827.86,   17127.98,   16451.10,   15811.52,
     15183.53,   14581.37,   13982.04,   13400.03,   12815.37,
     12248.19,   11678.54,   11126.48,   10572.09,   10035.43,
      9496.58,    8975.59,    8452.55,    7947.52,    7440.55,
      6931.96,    6442.38,    5956.41,    5498.04,    5050.84,
      4647.96,    4261.91,    3893.26,    3542.15,    3208.52,
      2892.23,    2593.71,    2312.95,    2049.75,    1803.89,
      1575.57,    1364.68,    1170.90,     993.84,     833.44,
       689.53,     561.52,     448.82,     350.95,     267.55,
       197.67,     137.23,      87.33,      48.44,      20.00,       0.00,
  pollat =$LM_NL_POLLATLM_C , pollon =$LM_NL_POLLONLM_C ,
  dlon=$LM_NL_DLONLM_C, dlat=$LM_NL_DLATLM_C,
  startlat_tot  = $LM_NL_STARTLAT_TOT_C,
  startlon_tot  = $LM_NL_STARTLON_TOT_C,
 /
 &DATA
  ylmext_form_read='ncdf',
  yinext_form_read='ncdf',
  yin_form_read='ncdf',
  ylm_form_write='ncdf',
  ie_ext=$LM_NL_EXT_IE_C, je_ext=$LM_NL_EXT_JE_C,
  ylmext_lfn='../bin/${LM_NL_EXTPAR_C}',
  yinext_lfn='cas${LM_YYYY_INI}${LM_MM_INI}${LM_DD_INI}${LM_ZZ_INI}0000.nc',
  yinext_cat='./input/',
  yin_cat='./input/',
  ylm_cat= './output/',
  nprocess_ini = 131, nprocess_bd = 132,
  yinput_type='analysis',
  ytunit_out='d',
 /END
 &PRICTR
 /
 &DATABASE
 / 
EOF

# setup job
# ---------

cat > job <<EOF_job_SLURM
#!/bin/bash
#SBATCH --job-name=ifs2lm
#SBATCH --output=job.out
#SBATCH --ntasks=$(( ${NQS_NXIFS2LM} * ${NQS_NYIFS2LM} + ${NQS_NIOIFS2LM} ))
#SBATCH --ntasks-per-node=12
#SBATCH --partition=${QUEUE}
#SBATCH --time=${NQS_ELAPSED_IFS2LM}
#SBATCH --account=${ACCOUNT}
EOF_job_SLURM

# rest of job (actual work)
cat >> job <<EOF_job

# Initialization
set verbose
set echo

# set environmental parameters
export OMP_NUM_THREADS=1
export MALLOC_MMAP_MAX_=0
export MALLOC_TRIM_THRESHOLD_=536870912
export MPICH_RDMA_ENABLED_CUDA=0
export MV2_USE_CUDA=0

# echo date
date

# Run LM in case directory
${RUNCMD} -u ${EXE_INT2LM}

# echo date
date

sacct -j \$SLURM_JOB_ID --format=User,JobID,Jobname,partition,state,time,start,end,elapsed,MaxRss,MaxVMSize,nnodes,ncpus,nodelist,AveCPUFreq

\rm -f .jobid >&/dev/null

EOF_job

# submit job
if [ -z "${WAITFORJOB}" ]; then
  jobid=`sbatch -C gpu job | sed 's/Submitted batch job //g'`
else
  jobid=`sbatch -C gpu --dependency=afterok:${WAITFORJOB} job | sed 's/Submitted batch job //g'`
fi

if [ $? -eq 0 -a -n "${jobid}" ]; then
  echo "${jobid}" > .jobid
  echo "${jobid}"
else
  exit 1
fi

