#!/bin/bash

# Update job status
update_status "running"

# clean
./clean

#Check if output folder exists
mkdir -p $(readlink output)

# Load modules
export OMP_NUM_THREADS=$CORES_PER_NODE
export CRAY_CUDA_MPS=1
module load daint-gpu
module load NCO

# Go to input dir
cd input

# Create missing links if needed
if [[ "${LM_COMPRESS_DIRS}" == *"lm_c"* ]]; then
    ln -sfn ../../20_lm_c/${LM_NL_OUTPUT_DIR_C} lm_c
fi
if [[ "${LM_COMPRESS_DIRS}" == *"lm_f"* ]]; then
    ln -sfn ../../40_lm_f/${LM_NL_OUTPUT_DIR_F} lm_f
fi
if [[ "${LM_COMPRESS_DIRS}" == *"cclm2_c"* ]]; then
    ln -sfn ../../20_cclm2_c/${LM_NL_OUTPUT_DIR_C} cclm2_c
fi

# Compress, archive and remove originals
for direc in ${LM_COMPRESS_DIRS}; do
    echo ${direc}
    nc_list=$(cosmo_file_list "${direc}" ">=" "${LM_BEGIN_DATE}" "<" "${LM_END_DATE}")
    if [[ -n ${nc_list} ]]; then
        # compress files
        echo "Compressing files"
        nfiles=0
        nerr=0
        nz_list=""
        for file in ${nc_list}; do
            ((nfiles++))
            echo "  $file"
            ofile=${file%.nc}.nz
            ncks -4 -L ${PACK_COMPRESS_LEVEL} --no_abc -O ${file} ${ofile}
            status=$?
            [[ -e ${ofile} && $status == 0 ]] && nz_list+=" ${ofile}" || ((nerr++))
        done
        if (( nerr > 0 )); then
            echo "something went wrong when compressing ${nerr}/${nfiles} files, exiting"
            exit 1
        fi

        if [[ ${PACK_CREATE_ARCHIVE} == true ]]; then
            # create archive
            part=$(dirname ${direc})
            stream=$(basename ${direc})
            tar_file="../output/${part}__${stream}__${LM_BEGIN_DATE_DG}-${LM_END_DATE_DG}.tar"
            echo "building archive file ${tar_file}"
            printf '%s\n' ${nz_list} > .nz_list.txt
            tar --transform='s/.nz/.nc/' -cvf ${tar_file} --files-from .nz_list.txt
            status=$?
            if [[ $status != 0 ]]; then
                echo "something went wrong when creating archive, exiting"
                exit $status
            fi

            # remove compressed and original files
            if [[ ${PACK_REMOVE_ORIGINAL} == true ]]; then
                echo "removing compressed and original files"
                nfiles=0
                nerr=0
                for file in ${nc_list} ${nz_list}; do
                    ((nfiles++))
                    rm -f ${file}
                    [[ $? != 0 ]] && ((nerr++))
                done
                if (( nerr > 0 )); then
                    echo "something went wrong when removing ${nerr}/${nfiles} compressed and original files, exiting"
                    exit 1
                fi
            fi
        else
            # Replace original nc files by compressed files
            echo "replacing original nc files by compressed files"
            nfiles=0
            nerr=0
            for file in ${nz_list}; do
                ((nfiles++))
                mv ${file} ${file%.nz}.nc
                [[ $? != 0 ]] && ((nerr++))
            done
            if (( nerr > 0 )); then
                echo "something went wrong when replacing ${nerr}/${nfiles} original nc files by compressed files, exiting"
                exit 1
            fi
        fi
    else
        echo "no nc files found in ${direc} between ${LM_BEGIN_DATE_FR} and ${LM_END_DATE_FR}"
    fi
done

# Update job status
update_status "done"
